// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCircuitBreaker creates a new instance of CircuitBreaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCircuitBreaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *CircuitBreaker {
	mock := &CircuitBreaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CircuitBreaker is an autogenerated mock type for the CircuitBreaker type
type CircuitBreaker struct {
	mock.Mock
}

type CircuitBreaker_Expecter struct {
	mock *mock.Mock
}

func (_m *CircuitBreaker) EXPECT() *CircuitBreaker_Expecter {
	return &CircuitBreaker_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type CircuitBreaker
func (_mock *CircuitBreaker) Execute(req func() (interface{}, error)) (interface{}, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(func() (interface{}, error)) (interface{}, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(func() (interface{}, error)) interface{}); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(func() (interface{}, error)) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CircuitBreaker_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CircuitBreaker_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - req func() (interface{}, error)
func (_e *CircuitBreaker_Expecter) Execute(req interface{}) *CircuitBreaker_Execute_Call {
	return &CircuitBreaker_Execute_Call{Call: _e.mock.On("Execute", req)}
}

func (_c *CircuitBreaker_Execute_Call) Run(run func(req func() (interface{}, error))) *CircuitBreaker_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func() (interface{}, error)
		if args[0] != nil {
			arg0 = args[0].(func() (interface{}, error))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CircuitBreaker_Execute_Call) Return(ifaceVal interface{}, err error) *CircuitBreaker_Execute_Call {
	_c.Call.Return(ifaceVal, err)
	return _c
}

func (_c *CircuitBreaker_Execute_Call) RunAndReturn(run func(req func() (interface{}, error)) (interface{}, error)) *CircuitBreaker_Execute_Call {
	_c.Call.Return(run)
	return _c
}
