dir: "{{.InterfaceDir}}/mocks/"
filename: "{{ .InterfaceName | snakecase }}.go"
formatter: goimports
structname: "{{.InterfaceName}}"
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/kroma-labs/sentinel-go/sql:
    config:
      all: true
  github.com/kroma-labs/sentinel-go/httpclient:
    config:
      all: true
