// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql/driver"

	mock "github.com/stretchr/testify/mock"
)

// NewDriverStmt creates a new instance of DriverStmt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriverStmt(t interface {
	mock.TestingT
	Cleanup(func())
}) *DriverStmt {
	mock := &DriverStmt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DriverStmt is an autogenerated mock type for the DriverStmt type
type DriverStmt struct {
	mock.Mock
}

type DriverStmt_Expecter struct {
	mock *mock.Mock
}

func (_m *DriverStmt) EXPECT() *DriverStmt_Expecter {
	return &DriverStmt_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type DriverStmt
func (_mock *DriverStmt) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DriverStmt_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DriverStmt_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DriverStmt_Expecter) Close() *DriverStmt_Close_Call {
	return &DriverStmt_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DriverStmt_Close_Call) Run(run func()) *DriverStmt_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DriverStmt_Close_Call) Return(err error) *DriverStmt_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DriverStmt_Close_Call) RunAndReturn(run func() error) *DriverStmt_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type DriverStmt
func (_mock *DriverStmt) Exec(args []driver.Value) (driver.Result, error) {
	ret := _mock.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 driver.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]driver.Value) (driver.Result, error)); ok {
		return returnFunc(args)
	}
	if returnFunc, ok := ret.Get(0).(func([]driver.Value) driver.Result); ok {
		r0 = returnFunc(args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]driver.Value) error); ok {
		r1 = returnFunc(args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverStmt_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type DriverStmt_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - args []driver.Value
func (_e *DriverStmt_Expecter) Exec(args interface{}) *DriverStmt_Exec_Call {
	return &DriverStmt_Exec_Call{Call: _e.mock.On("Exec", args)}
}

func (_c *DriverStmt_Exec_Call) Run(run func(args []driver.Value)) *DriverStmt_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []driver.Value
		if args[0] != nil {
			arg0 = args[0].([]driver.Value)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DriverStmt_Exec_Call) Return(result driver.Result, err error) *DriverStmt_Exec_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *DriverStmt_Exec_Call) RunAndReturn(run func(args []driver.Value) (driver.Result, error)) *DriverStmt_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function for the type DriverStmt
func (_mock *DriverStmt) ExecContext(ctx context.Context, args []driver.NamedValue) (driver.Result, error) {
	ret := _mock.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 driver.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []driver.NamedValue) (driver.Result, error)); ok {
		return returnFunc(ctx, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []driver.NamedValue) driver.Result); ok {
		r0 = returnFunc(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []driver.NamedValue) error); ok {
		r1 = returnFunc(ctx, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverStmt_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type DriverStmt_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - args []driver.NamedValue
func (_e *DriverStmt_Expecter) ExecContext(ctx interface{}, args interface{}) *DriverStmt_ExecContext_Call {
	return &DriverStmt_ExecContext_Call{Call: _e.mock.On("ExecContext", ctx, args)}
}

func (_c *DriverStmt_ExecContext_Call) Run(run func(ctx context.Context, args []driver.NamedValue)) *DriverStmt_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []driver.NamedValue
		if args[1] != nil {
			arg1 = args[1].([]driver.NamedValue)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DriverStmt_ExecContext_Call) Return(result driver.Result, err error) *DriverStmt_ExecContext_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *DriverStmt_ExecContext_Call) RunAndReturn(run func(ctx context.Context, args []driver.NamedValue) (driver.Result, error)) *DriverStmt_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// NumInput provides a mock function for the type DriverStmt
func (_mock *DriverStmt) NumInput() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NumInput")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// DriverStmt_NumInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NumInput'
type DriverStmt_NumInput_Call struct {
	*mock.Call
}

// NumInput is a helper method to define mock.On call
func (_e *DriverStmt_Expecter) NumInput() *DriverStmt_NumInput_Call {
	return &DriverStmt_NumInput_Call{Call: _e.mock.On("NumInput")}
}

func (_c *DriverStmt_NumInput_Call) Run(run func()) *DriverStmt_NumInput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DriverStmt_NumInput_Call) Return(n int) *DriverStmt_NumInput_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *DriverStmt_NumInput_Call) RunAndReturn(run func() int) *DriverStmt_NumInput_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type DriverStmt
func (_mock *DriverStmt) Query(args []driver.Value) (driver.Rows, error) {
	ret := _mock.Called(args)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 driver.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]driver.Value) (driver.Rows, error)); ok {
		return returnFunc(args)
	}
	if returnFunc, ok := ret.Get(0).(func([]driver.Value) driver.Rows); ok {
		r0 = returnFunc(args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]driver.Value) error); ok {
		r1 = returnFunc(args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverStmt_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type DriverStmt_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - args []driver.Value
func (_e *DriverStmt_Expecter) Query(args interface{}) *DriverStmt_Query_Call {
	return &DriverStmt_Query_Call{Call: _e.mock.On("Query", args)}
}

func (_c *DriverStmt_Query_Call) Run(run func(args []driver.Value)) *DriverStmt_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []driver.Value
		if args[0] != nil {
			arg0 = args[0].([]driver.Value)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DriverStmt_Query_Call) Return(rows driver.Rows, err error) *DriverStmt_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *DriverStmt_Query_Call) RunAndReturn(run func(args []driver.Value) (driver.Rows, error)) *DriverStmt_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function for the type DriverStmt
func (_mock *DriverStmt) QueryContext(ctx context.Context, args []driver.NamedValue) (driver.Rows, error) {
	ret := _mock.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 driver.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []driver.NamedValue) (driver.Rows, error)); ok {
		return returnFunc(ctx, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []driver.NamedValue) driver.Rows); ok {
		r0 = returnFunc(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []driver.NamedValue) error); ok {
		r1 = returnFunc(ctx, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverStmt_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type DriverStmt_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - args []driver.NamedValue
func (_e *DriverStmt_Expecter) QueryContext(ctx interface{}, args interface{}) *DriverStmt_QueryContext_Call {
	return &DriverStmt_QueryContext_Call{Call: _e.mock.On("QueryContext", ctx, args)}
}

func (_c *DriverStmt_QueryContext_Call) Run(run func(ctx context.Context, args []driver.NamedValue)) *DriverStmt_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []driver.NamedValue
		if args[1] != nil {
			arg1 = args[1].([]driver.NamedValue)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DriverStmt_QueryContext_Call) Return(rows driver.Rows, err error) *DriverStmt_QueryContext_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *DriverStmt_QueryContext_Call) RunAndReturn(run func(ctx context.Context, args []driver.NamedValue) (driver.Rows, error)) *DriverStmt_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}
