// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewDriverTx creates a new instance of DriverTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriverTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *DriverTx {
	mock := &DriverTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DriverTx is an autogenerated mock type for the DriverTx type
type DriverTx struct {
	mock.Mock
}

type DriverTx_Expecter struct {
	mock *mock.Mock
}

func (_m *DriverTx) EXPECT() *DriverTx_Expecter {
	return &DriverTx_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type DriverTx
func (_mock *DriverTx) Commit() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DriverTx_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type DriverTx_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *DriverTx_Expecter) Commit() *DriverTx_Commit_Call {
	return &DriverTx_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *DriverTx_Commit_Call) Run(run func()) *DriverTx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DriverTx_Commit_Call) Return(err error) *DriverTx_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DriverTx_Commit_Call) RunAndReturn(run func() error) *DriverTx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type DriverTx
func (_mock *DriverTx) Rollback() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DriverTx_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type DriverTx_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *DriverTx_Expecter) Rollback() *DriverTx_Rollback_Call {
	return &DriverTx_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *DriverTx_Rollback_Call) Run(run func()) *DriverTx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DriverTx_Rollback_Call) Return(err error) *DriverTx_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DriverTx_Rollback_Call) RunAndReturn(run func() error) *DriverTx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}
