// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"database/sql/driver"

	mock "github.com/stretchr/testify/mock"
)

// NewDriverRows creates a new instance of DriverRows. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriverRows(t interface {
	mock.TestingT
	Cleanup(func())
}) *DriverRows {
	mock := &DriverRows{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DriverRows is an autogenerated mock type for the DriverRows type
type DriverRows struct {
	mock.Mock
}

type DriverRows_Expecter struct {
	mock *mock.Mock
}

func (_m *DriverRows) EXPECT() *DriverRows_Expecter {
	return &DriverRows_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type DriverRows
func (_mock *DriverRows) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DriverRows_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DriverRows_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DriverRows_Expecter) Close() *DriverRows_Close_Call {
	return &DriverRows_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DriverRows_Close_Call) Run(run func()) *DriverRows_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DriverRows_Close_Call) Return(err error) *DriverRows_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DriverRows_Close_Call) RunAndReturn(run func() error) *DriverRows_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Columns provides a mock function for the type DriverRows
func (_mock *DriverRows) Columns() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Columns")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// DriverRows_Columns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Columns'
type DriverRows_Columns_Call struct {
	*mock.Call
}

// Columns is a helper method to define mock.On call
func (_e *DriverRows_Expecter) Columns() *DriverRows_Columns_Call {
	return &DriverRows_Columns_Call{Call: _e.mock.On("Columns")}
}

func (_c *DriverRows_Columns_Call) Run(run func()) *DriverRows_Columns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DriverRows_Columns_Call) Return(strings []string) *DriverRows_Columns_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *DriverRows_Columns_Call) RunAndReturn(run func() []string) *DriverRows_Columns_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type DriverRows
func (_mock *DriverRows) Next(dest []driver.Value) error {
	ret := _mock.Called(dest)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]driver.Value) error); ok {
		r0 = returnFunc(dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DriverRows_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type DriverRows_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - dest []driver.Value
func (_e *DriverRows_Expecter) Next(dest interface{}) *DriverRows_Next_Call {
	return &DriverRows_Next_Call{Call: _e.mock.On("Next", dest)}
}

func (_c *DriverRows_Next_Call) Run(run func(dest []driver.Value)) *DriverRows_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []driver.Value
		if args[0] != nil {
			arg0 = args[0].([]driver.Value)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DriverRows_Next_Call) Return(err error) *DriverRows_Next_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DriverRows_Next_Call) RunAndReturn(run func(dest []driver.Value) error) *DriverRows_Next_Call {
	_c.Call.Return(run)
	return _c
}
