// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql/driver"

	mock "github.com/stretchr/testify/mock"
)

// NewDriverConnector creates a new instance of DriverConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriverConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *DriverConnector {
	mock := &DriverConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DriverConnector is an autogenerated mock type for the DriverConnector type
type DriverConnector struct {
	mock.Mock
}

type DriverConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *DriverConnector) EXPECT() *DriverConnector_Expecter {
	return &DriverConnector_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type DriverConnector
func (_mock *DriverConnector) Connect(ctx context.Context) (driver.Conn, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 driver.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (driver.Conn, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) driver.Conn); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverConnector_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type DriverConnector_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DriverConnector_Expecter) Connect(ctx interface{}) *DriverConnector_Connect_Call {
	return &DriverConnector_Connect_Call{Call: _e.mock.On("Connect", ctx)}
}

func (_c *DriverConnector_Connect_Call) Run(run func(ctx context.Context)) *DriverConnector_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DriverConnector_Connect_Call) Return(conn driver.Conn, err error) *DriverConnector_Connect_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *DriverConnector_Connect_Call) RunAndReturn(run func(ctx context.Context) (driver.Conn, error)) *DriverConnector_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Driver provides a mock function for the type DriverConnector
func (_mock *DriverConnector) Driver() driver.Driver {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Driver")
	}

	var r0 driver.Driver
	if returnFunc, ok := ret.Get(0).(func() driver.Driver); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Driver)
		}
	}
	return r0
}

// DriverConnector_Driver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Driver'
type DriverConnector_Driver_Call struct {
	*mock.Call
}

// Driver is a helper method to define mock.On call
func (_e *DriverConnector_Expecter) Driver() *DriverConnector_Driver_Call {
	return &DriverConnector_Driver_Call{Call: _e.mock.On("Driver")}
}

func (_c *DriverConnector_Driver_Call) Run(run func()) *DriverConnector_Driver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DriverConnector_Driver_Call) Return(driver1 driver.Driver) *DriverConnector_Driver_Call {
	_c.Call.Return(driver1)
	return _c
}

func (_c *DriverConnector_Driver_Call) RunAndReturn(run func() driver.Driver) *DriverConnector_Driver_Call {
	_c.Call.Return(run)
	return _c
}
