// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql/driver"

	mock "github.com/stretchr/testify/mock"
)

// NewDriverConn creates a new instance of DriverConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriverConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *DriverConn {
	mock := &DriverConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DriverConn is an autogenerated mock type for the DriverConn type
type DriverConn struct {
	mock.Mock
}

type DriverConn_Expecter struct {
	mock *mock.Mock
}

func (_m *DriverConn) EXPECT() *DriverConn_Expecter {
	return &DriverConn_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type DriverConn
func (_mock *DriverConn) Begin() (driver.Tx, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 driver.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (driver.Tx, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() driver.Tx); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverConn_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type DriverConn_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *DriverConn_Expecter) Begin() *DriverConn_Begin_Call {
	return &DriverConn_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *DriverConn_Begin_Call) Run(run func()) *DriverConn_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DriverConn_Begin_Call) Return(tx driver.Tx, err error) *DriverConn_Begin_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *DriverConn_Begin_Call) RunAndReturn(run func() (driver.Tx, error)) *DriverConn_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function for the type DriverConn
func (_mock *DriverConn) BeginTx(ctx context.Context, opts driver.TxOptions) (driver.Tx, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 driver.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, driver.TxOptions) (driver.Tx, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, driver.TxOptions) driver.Tx); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, driver.TxOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverConn_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type DriverConn_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts driver.TxOptions
func (_e *DriverConn_Expecter) BeginTx(ctx interface{}, opts interface{}) *DriverConn_BeginTx_Call {
	return &DriverConn_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *DriverConn_BeginTx_Call) Run(run func(ctx context.Context, opts driver.TxOptions)) *DriverConn_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 driver.TxOptions
		if args[1] != nil {
			arg1 = args[1].(driver.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DriverConn_BeginTx_Call) Return(tx driver.Tx, err error) *DriverConn_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *DriverConn_BeginTx_Call) RunAndReturn(run func(ctx context.Context, opts driver.TxOptions) (driver.Tx, error)) *DriverConn_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type DriverConn
func (_mock *DriverConn) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DriverConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DriverConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DriverConn_Expecter) Close() *DriverConn_Close_Call {
	return &DriverConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DriverConn_Close_Call) Run(run func()) *DriverConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DriverConn_Close_Call) Return(err error) *DriverConn_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DriverConn_Close_Call) RunAndReturn(run func() error) *DriverConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function for the type DriverConn
func (_mock *DriverConn) ExecContext(ctx context.Context, query string, args []driver.NamedValue) (driver.Result, error) {
	ret := _mock.Called(ctx, query, args)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 driver.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []driver.NamedValue) (driver.Result, error)); ok {
		return returnFunc(ctx, query, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []driver.NamedValue) driver.Result); ok {
		r0 = returnFunc(ctx, query, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []driver.NamedValue) error); ok {
		r1 = returnFunc(ctx, query, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverConn_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type DriverConn_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args []driver.NamedValue
func (_e *DriverConn_Expecter) ExecContext(ctx interface{}, query interface{}, args interface{}) *DriverConn_ExecContext_Call {
	return &DriverConn_ExecContext_Call{Call: _e.mock.On("ExecContext", ctx, query, args)}
}

func (_c *DriverConn_ExecContext_Call) Run(run func(ctx context.Context, query string, args []driver.NamedValue)) *DriverConn_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []driver.NamedValue
		if args[2] != nil {
			arg2 = args[2].([]driver.NamedValue)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DriverConn_ExecContext_Call) Return(result driver.Result, err error) *DriverConn_ExecContext_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *DriverConn_ExecContext_Call) RunAndReturn(run func(ctx context.Context, query string, args []driver.NamedValue) (driver.Result, error)) *DriverConn_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type DriverConn
func (_mock *DriverConn) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DriverConn_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type DriverConn_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DriverConn_Expecter) Ping(ctx interface{}) *DriverConn_Ping_Call {
	return &DriverConn_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *DriverConn_Ping_Call) Run(run func(ctx context.Context)) *DriverConn_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DriverConn_Ping_Call) Return(err error) *DriverConn_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DriverConn_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *DriverConn_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type DriverConn
func (_mock *DriverConn) Prepare(query string) (driver.Stmt, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 driver.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (driver.Stmt, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) driver.Stmt); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverConn_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type DriverConn_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - query string
func (_e *DriverConn_Expecter) Prepare(query interface{}) *DriverConn_Prepare_Call {
	return &DriverConn_Prepare_Call{Call: _e.mock.On("Prepare", query)}
}

func (_c *DriverConn_Prepare_Call) Run(run func(query string)) *DriverConn_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DriverConn_Prepare_Call) Return(stmt driver.Stmt, err error) *DriverConn_Prepare_Call {
	_c.Call.Return(stmt, err)
	return _c
}

func (_c *DriverConn_Prepare_Call) RunAndReturn(run func(query string) (driver.Stmt, error)) *DriverConn_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareContext provides a mock function for the type DriverConn
func (_mock *DriverConn) PrepareContext(ctx context.Context, query string) (driver.Stmt, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 driver.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (driver.Stmt, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) driver.Stmt); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverConn_PrepareContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareContext'
type DriverConn_PrepareContext_Call struct {
	*mock.Call
}

// PrepareContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *DriverConn_Expecter) PrepareContext(ctx interface{}, query interface{}) *DriverConn_PrepareContext_Call {
	return &DriverConn_PrepareContext_Call{Call: _e.mock.On("PrepareContext", ctx, query)}
}

func (_c *DriverConn_PrepareContext_Call) Run(run func(ctx context.Context, query string)) *DriverConn_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DriverConn_PrepareContext_Call) Return(stmt driver.Stmt, err error) *DriverConn_PrepareContext_Call {
	_c.Call.Return(stmt, err)
	return _c
}

func (_c *DriverConn_PrepareContext_Call) RunAndReturn(run func(ctx context.Context, query string) (driver.Stmt, error)) *DriverConn_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function for the type DriverConn
func (_mock *DriverConn) QueryContext(ctx context.Context, query string, args []driver.NamedValue) (driver.Rows, error) {
	ret := _mock.Called(ctx, query, args)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 driver.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []driver.NamedValue) (driver.Rows, error)); ok {
		return returnFunc(ctx, query, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []driver.NamedValue) driver.Rows); ok {
		r0 = returnFunc(ctx, query, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []driver.NamedValue) error); ok {
		r1 = returnFunc(ctx, query, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DriverConn_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type DriverConn_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args []driver.NamedValue
func (_e *DriverConn_Expecter) QueryContext(ctx interface{}, query interface{}, args interface{}) *DriverConn_QueryContext_Call {
	return &DriverConn_QueryContext_Call{Call: _e.mock.On("QueryContext", ctx, query, args)}
}

func (_c *DriverConn_QueryContext_Call) Run(run func(ctx context.Context, query string, args []driver.NamedValue)) *DriverConn_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []driver.NamedValue
		if args[2] != nil {
			arg2 = args[2].([]driver.NamedValue)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DriverConn_QueryContext_Call) Return(rows driver.Rows, err error) *DriverConn_QueryContext_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *DriverConn_QueryContext_Call) RunAndReturn(run func(ctx context.Context, query string, args []driver.NamedValue) (driver.Rows, error)) *DriverConn_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}
